spring.application.name=ratemusic
spring.datasource.url=jdbc:mysql://localhost:3306/ratemusic_db
spring.datasource.username=root
spring.datasource.password=lim47812
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
jwt.secret="the-secret-key-must-be-hidden-in-this-file"
